// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blogs.sql

package database

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (title, content, tags)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, title, content, tags, createdat, updatedat
`

type CreateBlogParams struct {
	Title   string
	Content string
	Tags    sql.NullString
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog, arg.Title, arg.Content, arg.Tags)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
