// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blogs.sql

package database

import (
	"context"
	"encoding/json"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (title, content, category, tags)
VALUES (
    ?,
    ?,
    ?,
    ?
)
RETURNING id, title, content, category, tags, createdat, updatedat
`

type CreateBlogParams struct {
	Title    string
	Content  string
	Category string
	Tags     json.RawMessage
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Tags,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :one
DELETE FROM blogs
WHERE id = ?
RETURNING title
`

func (q *Queries) DeleteBlog(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteBlog, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getBlog = `-- name: GetBlog :one
SELECT id, title, content, category, tags, createdat, updatedat FROM blogs
WHERE id = ?
`

func (q *Queries) GetBlog(ctx context.Context, id int64) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET title = ?, content = ?, category = ?, tags = ?, updatedAt = current_timestamp
WHERE id = ?
RETURNING id, title, content, category, tags, createdat, updatedat
`

type UpdateBlogParams struct {
	Title    string
	Content  string
	Category string
	Tags     json.RawMessage
	ID       int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, updateBlog,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Tags,
		arg.ID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
