// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Blog struct {
	ID        int64
	Title     string
	Content   string
	Tags      sql.NullString
	Createdat sql.NullTime
	Updatedat sql.NullTime
}
