// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"
	"time"
)

type Blog struct {
	ID        int64
	Title     string
	Content   string
	Category  string
	Tags      json.RawMessage
	Createdat time.Time
	Updatedat time.Time
}
